version: 0.0
os: linux

files:
  - source: /index.html
    destination: /var/www/html/
  - source: /styles/
    destination: /var/www/html/styles/
  - source: /assets/
    destination: /var/www/html/assets/

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/set_permissions.sh  # Set file permissions
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
